version: '3.1'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: starwars
      POSTGRES_PASSWORD: stat
      POSTGRES_DB: starwars
    ports:
      - 5490:5432
  adminer:
    image: adminer
    restart: always
    ports:
      - 7000:8080
